### ISSUE TITLE
REDCap's data entry page provides a button that circumvents the linear workflow

### ISSUE THREAD

**Issue by rajputd** [ctsit/linear_data_entry_workflow#14]
Here is an example:

![image](https://user-images.githubusercontent.com/16458008/29187255-0f690476-7ddd-11e7-838a-af29ee822c43.png)

Note the "Save & Go To Next Form Button" in the upper right. It can be used to access forms that the user should not be able to access.

**Comment by pbchase** [comment]
@tbembersimeao says it's done
