### ISSUE TITLE
'Save & Go To Next Record' should be hideable

### ISSUE THREAD

**Issue by pbchase** [ctsit/linear_data_entry_workflow#18]
The "Save & Go To Next Record" button is probably a distraction for the Reveal Forms In Order (RFIO) functionality. Add a project-level configurable option to hide it. Hide it on every form in the project. The id of the field to be hidden is 'submit-btn-savenextrecord'.

**Comment by tbembersimeao** [comment]
https://github.com/ctsit/linear_data_entry_workflow/pull/19
