### ISSUE TITLE
rfio_record_home.php has no effect

### ISSUE THREAD

**Issue by pbchase** [ctsit/linear_data_entry_workflow#2]
In testing [rfio_record_home.php](https://github.com/ctsit/linear_data_entry_workflow/blob/develop/rfio_record_home.php) has no affect. The other two rfio hooks work correctly, but the record_home hook shows all forms events accessible at all times. Here's the hooks directory in which these hooks are deployed.  

`vagrant@redcap-deployment:/var/www$ find redcap/hooks/
redcap/hooks/
redcap/hooks/pid13
redcap/hooks/pid13/redcap_every_page_top
redcap/hooks/pid13/redcap_every_page_top/frsl_dashboard.php
redcap/hooks/pid13/redcap_every_page_top/frsl_record_home_page.php
redcap/hooks/pid13/redcap_every_page_top/frsl_data_collection_instruments.php
redcap/hooks/redcap_every_page_top
redcap/hooks/redcap_every_page_top/cps_hook.php
redcap/hooks/pid17
redcap/hooks/pid17/redcap_data_entry_form
redcap/hooks/pid17/redcap_data_entry_form/default_from_field.php
redcap/hooks/pid17/redcap_data_entry_form/force_data_entry_constraints.php
redcap/hooks/pid17/redcap_data_entry_form/copy_values_from_previous_event.php
redcap/hooks/pid17/redcap_every_page_top
redcap/hooks/pid17/redcap_every_page_top/rfio_dashboard.php
redcap/hooks/pid17/redcap_every_page_top/rfio_record_home.php
redcap/hooks/pid17/redcap_every_page_top/rfio_data_entry.php
redcap/hooks/pid17/redcap_every_page_top/default_from_field_help.php
redcap/hooks/README.md
redcap/hooks/redcap_hooks.php
redcap/hooks/index.html
redcap/hooks/pid16
redcap/hooks/pid16/redcap_data_entry_form
redcap/hooks/pid16/redcap_data_entry_form/default_from_field.php
redcap/hooks/pid16/redcap_data_entry_form/force_data_entry_constraints.php
redcap/hooks/pid16/redcap_data_entry_form/copy_values_from_previous_event.php
redcap/hooks/pid16/redcap_every_page_top
redcap/hooks/pid16/redcap_every_page_top/default_from_field_help.php
redcap/hooks/library
redcap/hooks/library/redcap_data_entry_form
redcap/hooks/library/redcap_data_entry_form/complex_validation.php
redcap/hooks/library/redcap_data_entry_form/default_from_field.php
redcap/hooks/library/redcap_data_entry_form/force_data_entry_constraints.php
redcap/hooks/library/redcap_data_entry_form/copy_values_from_previous_event.php
redcap/hooks/library/redcap_every_page_top
redcap/hooks/library/redcap_every_page_top/frsl_dashboard.php
redcap/hooks/library/redcap_every_page_top/cps_hook.php
redcap/hooks/library/redcap_every_page_top/frsl_record_home_page.php
redcap/hooks/library/redcap_every_page_top/modify_contact_admin_button.php
redcap/hooks/library/redcap_every_page_top/rfio_dashboard.php
redcap/hooks/library/redcap_every_page_top/rfio_record_home.php
redcap/hooks/library/redcap_every_page_top/rfio_data_entry.php
redcap/hooks/library/redcap_every_page_top/frsl_data_collection_instruments.php
redcap/hooks/library/redcap_every_page_top/default_from_field_help.php`

In the example, project 17 is the testing project.

**Comment by rajputd** [comment]
There is a mistake in the README. rfio_data_entry.php is supposed to be activated using:

`fab instance:vagrant activate_hook:redcap_data_entry_form,rfio_data_entry.php,$MYPID`

On the record home page rfio_data_entry runs before rfio_record_home, crashes, and stops rfio_record_home from ever activating.

**Comment by rajputd** [comment]
There is a mistake in the README. rfio_data_entry.php is supposed to be activated using:

`fab instance:vagrant activate_hook:redcap_data_entry_form,rfio_data_entry.php,$MYPID`

The issue is that rfio_data_entry is being activated in the wrong place. On the record home page it runs before rfio_record_home, crashes, and stops rfio_record_home from activating.

**Comment by pbchase** [comment]
Fixed by commit a80d734
