### ISSUE TITLE
Repeating forms block future forms

### ISSUE THREAD

**Issue by pbchase** [ctsit/linear_data_entry_workflow#28]
A repeating form will block access to future forms in the same event unless the repeating is in the exception list.  A repeating form will block access to forms in the next event _even if_ the repeating is in the exception list. This error was found in REDCap 8.0.3.

**Comment by pbchase** [comment]
FYI, @tlstoffs found this one in Warrior Prod.

**Comment by tbembersimeao** [comment]
Nice catch! Here is a fix for that: #29.
