### ISSUE TITLE
Remove access to subsequent forms if the current forms are not filled.

### ISSUE THREAD

**Issue by suryaprasanna** [ctsit/linear_data_entry_workflow#4]

**Comment by pbchase** [comment]
@suryaprasanna , please checkout the latest code and review.  I think this is fixed by commit 7015f24

**Comment by suryaprasanna** [comment]
@pbchase , sure I will test the functionality once. On monday, when I checked I was able to open the next forms by changing the url.

**Comment by suryaprasanna** [comment]
Closing this issue as it not having a major problem.
