### ISSUE TITLE
Required field rules not enforced on files and signatures

### ISSUE THREAD

**Issue by pbchase** [ctsit/linear_data_entry_workflow#42]
REDCap's required field rules not enforced on in fields with a type of _file upload_ or _signature_. The ignore button is presented and the form is saved as complete when either of these file types is marked as required but not filled in. I've provided some screenshots of the problem

![required upload field failure](https://user-images.githubusercontent.com/3356493/50239046-0f18c900-038f-11e9-8db7-3484edd1a5bc.png)
![Required signature field failure](https://user-images.githubusercontent.com/3356493/50239045-0f18c900-038f-11e9-8611-244ef06a5706.png)

I have also provided a small REDCap project that can be used to reproduce the problem. [LdewfTest_2018-12-19_1305.REDCap.xml.txt](https://github.com/ctsit/linear_data_entry_workflow/files/2696039/LdewfTest_2018-12-19_1305.REDCap.xml.txt) Remove the .txt extension to use it to build a REDCap test project.

These tests were done in REDCap 8.2.2 with LDEWF 2.5.1

**Comment by ChemiKyle** [comment]
Issue is here:  
https://github.com/ctsit/linear_data_entry_workflow/blob/14375c4f88e2a1c38506a0f5e60afa88f21f2553/js/fdec.js#L95

The `required_fields_selector` does not properly identify signature fields.

**Comment by ChemiKyle** [comment]
Addressed by #52
