### ISSUE TITLE
LDEW is allowing forms to be marked as complete when required fields are not filled in

### ISSUE THREAD

**Issue by pbchase** [ctsit/linear_data_entry_workflow#43]
LDEW is allowing forms to be marked as complete when required fields are not filled in under REDCap 9.1.1. This is what the README says the FDEC feature is supposed to do:

```
Force Data Entry Constraints (FDEC)

This feature prevents users from marking a form as complete if the required
fields are not filled in. Additionally, field verifications must be satisfied
before the form can be marked Completed.

For example, if the field 'Age' requires a number from 0 to 99 and the user
enters 'fifty' the form cannot be marked as complete. If the user attempts to
mark the form complete with an empty field or unverified field, a popup window
will direct them to the field(s) that need to be adjusted before they can mark
the form complete.
```
This error might have been introduced between REDCap 8.11.2 and 9.1.1

**Comment by ChemiKyle** [comment]
A basic test in 9.1.1 results in a successful block, will need to see error.

![Screen Shot 2019-07-30 at 2 20 11 PM](https://user-images.githubusercontent.com/20332546/62154690-3e07fd80-b2d5-11e9-8225-a0dc49628a2b.png)

**Comment by pbchase** [comment]
The docs say "This feature prevents users from marking a form as complete if the required
fields are not filled in." Taryn and I recall that this was implemented by javascript code dynamically hiding and exposing the "Complete" option in the "Complete?" field, yet there it is in RC 9.1.1

**Comment by ChemiKyle** [comment]
Oh! I interpreted that as disabling the ability to mark as complete and _then_ save anyway after the warning (which it does).
