### ISSUE TITLE
Form Exceptions breaks functionality

### ISSUE THREAD

**Issue by h3n0r1k** [ctsit/linear_data_entry_workflow#48]
![bug1](https://user-images.githubusercontent.com/33369183/80696781-38e01500-8ad8-11ea-852e-09e523eee8d1.PNG)
hey!

i have mutliple Forms/Visists. Everytime I configure an Exception for the last Form/Visit, all Forms before that one become accessible.

Is that a bug or is the error on my side?

I did attach a screenshot. All yellow marked Forms shouldnt be available. It works if i have no Exception for "Dropout". If I make an exception for "Dropout" all other Forms become accessible.

BR
h3n0r1k

**Comment by ChemiKyle** [comment]
Hi @h3n0r1k,

What version of REDCap and what version of Linear Data Entry Workflow are you using? Could you please share the project XML (you'll have to put it in a `.zip` file to share it here)?

**Comment by h3n0r1k** [comment]
Hey Kyle!

We are using version REDCap 9.5.24. I'll attach the Project file. Thanks for you help.
[2020-05-04_0915.REDCap.xml.zip](https://github.com/ctsit/linear_data_entry_workflow/files/4573206/2020-05-04_0915.REDCap.xml.zip)

**Comment by ChemiKyle** [comment]
I am able to recreate this error using REDcap 9.5.24. The error does not show up if any other event is selected.  
I see errors in the javascript console when accessing the module level configuration for this module. The errors appear to be in REDCap core code.

**Comment by ChemiKyle** [comment]
The error is in `js/rfio.js`, in this case on this line:  
https://github.com/ctsit/linear_data_entry_workflow/blob/f76ea7c1be043f1e45f30a30872a275da6bf60c4/js/rfio.js#L44

The `settings.deniedForms` object is lacking an entry at the 3rd level, `page`.

**Comment by ChemiKyle** [comment]
@h3n0r1k I have a code solution for this issue submitted, it will have to be reviewed before it can be released. If you need this to work _now_ there is a design solution: move your Studienende/Abbruch event to occur earlier or assign the instrument to appear in any earlier event (such as Baseline). Both of these are kind of odd design choices but I thought I'd let you know in case it may be useful.

**Comment by pbchase** [comment]
Closed by PR #50.  @h3n0r1k, I'll release this as version 2.5.3 and submit this to the REDCap repo tonight. Thanks for the detailed bug report. :-)

**Comment by h3n0r1k** [comment]
Thanks alot for your awesome work!

**Comment by h3n0r1k** [comment]
Unfortunately for me its still the same bug. 
Or did I do something wrong? I'll attach Screenshots and the Project XML.
We are still on version REDCap 9.5.24. I did update LDEW to 2.5.3.

![ldew_config](https://user-images.githubusercontent.com/33369183/81142058-c6a38080-8f6e-11ea-8bc6-19122b2ac1f8.png)
![ldew_dashboard](https://user-images.githubusercontent.com/33369183/81142059-c73c1700-8f6e-11ea-8833-a2c05926fc0a.png)

[DammREGIMSTestversio_2020-05-06_0753.REDCap.xml.zip](https://github.com/ctsit/linear_data_entry_workflow/files/4584990/DammREGIMSTestversio_2020-05-06_0753.REDCap.xml.zip)

Thanks for your help

**Comment by h3n0r1k** [comment]
I did some testint with your Example project and can reproduce the bug. I'll attach the xml from your example with reproduced bug. The project is a bit cleaner then :)

[A_2020-05-06_0829.REDCap.xml.zip](https://github.com/ctsit/linear_data_entry_workflow/files/4585107/A_2020-05-06_0829.REDCap.xml.zip)

**Comment by h3n0r1k** [comment]
There is some weird interaction. In the screenshot below only "d" is defined as exception. When i delete Visit 5, everything works as intended, but with visit 5 it breaks. Hope that helps somehow.


![2020-05-06 08_40_46-a _ REDCap_bug](https://user-images.githubusercontent.com/33369183/81144548-9bbc2b00-8f74-11ea-950f-00d17eeb3af3.png)

**Comment by ChemiKyle** [comment]
Thanks @h3n0r1k the additional screenshots and use of our project are very helpful!

When I fixed this I _only_ set "Dropout" as an exception, quickly using your old project XML and setting both Schwangerschaft forms as exceptions in addition to Studienende/Abbruch I can recreate the error again. Can you confirm that LDEW version 2.5.3 works as expected with only Studienende/Abbruch as an exception?

**Comment by h3n0r1k** [comment]
hey kyle,

yes, only putting Studienende/Abbruch as an exception does work. 

BR!

**Comment by ChemiKyle** [comment]
@h3n0r1k could you please attach the XML for the project you took screenshots of in [this comment](https://github.com/ctsit/linear_data_entry_workflow/issues/48#issuecomment-624468716)? I manually added forms a-d but with only d as an exception I am not seeing the bug with event 5 present:

![image](https://user-images.githubusercontent.com/20332546/81190238-8f8c9980-8f85-11ea-8195-e827aa23e418.png)


![image](https://user-images.githubusercontent.com/20332546/81190119-6409af00-8f85-11ea-8d17-49e8cc5baabf.png)

**Comment by h3n0r1k** [comment]
Sorry not at work anymore! I'll provide you the XML tomorrow asap.

**Comment by h3n0r1k** [comment]
Hello,

xml is attached, if still needed! 

[A_2020-05-07_0748.REDCap.xml.zip](https://github.com/ctsit/linear_data_entry_workflow/files/4590919/A_2020-05-07_0748.REDCap.xml.zip)

**Comment by ChemiKyle** [comment]
@h3n0r1k there must have been a mistake, this isn't the project XML I was expecting. In the screenshots included in your earlier comment you have instruments labeled a, b, c, and d:

> There is some weird interaction. In the screenshot below only "d" is defined as exception. When i delete Visit 5, everything works as intended, but with visit 5 it breaks. Hope that helps somehow.
> 
> ![2020-05-06 08_40_46-a _ REDCap_bug](https://user-images.githubusercontent.com/33369183/81144548-9bbc2b00-8f74-11ea-950f-00d17eeb3af3.png)
> 
> ![2020-05-06 08_42_49-a _ REDCapD](https://user-images.githubusercontent.com/33369183/81144677-dc1ba900-8f74-11ea-9766-eb2c04dba868.png)

The XML provided looks like this:  
![image](https://user-images.githubusercontent.com/20332546/81308089-646e7c80-904f-11ea-9642-877e39ee32de.png)

**Comment by h3n0r1k** [comment]
hey, sorry for the wrong upload. 

[A_2020-05-08_0757.REDCap.xml.zip](https://github.com/ctsit/linear_data_entry_workflow/files/4597219/A_2020-05-08_0757.REDCap.xml.zip)

This should defenitly be the right one!
BR

**Comment by ChemiKyle** [comment]
@h3n0r1k this is still the wrong XML file. There are a few cases where project XML exports do not exactly copy the project; these cases unfortunately escape me at the moment but I believe they only occur with repeating instances of events or forms which is not the case here.

**Comment by h3n0r1k** [comment]
Hi @ChemiKyle 
I did try an export/import again and there seems to be some issue with importing :D. I did provide you the correct xml file but for some reason the visists dont show up on importing... But if you go to manage your visists and assign forms to visits you should see visist 2,3 and 6. Only 5 should not be there because i deleted it for the test, but you can just add a visist 5 again.

Hope that helps and thanks a lot for your work!

**Comment by ChemiKyle** [comment]
@h3n0r1k, I guess there are more shortcomings for the XMLs than I thought! What I was really after was getting your a, b, c, and d instruments which were not in the XML you provided at all. However, by using the XML you provided and adding in those instruments I can finally recreate your bug! Luckily, I also see that [the PR I have out](https://github.com/ctsit/linear_data_entry_workflow/pull/51) addressing the initial issue you reported also fixes this bug.

I created a project last week to try to recreate your issue and despite looking identical to yours the bug does not occur with event 5 enabled. While I wait for review, would you mind using [this project XML](https://github.com/ctsit/linear_data_entry_workflow/files/4615997/LDEW_48-2.zip) and seeing if the bug still manifests for you? I've provided screenshots of relevant configurations, hopefully the English page titles are close to the German.  

"Designate Instruments for My Events":  
![image](https://user-images.githubusercontent.com/20332546/81700206-5eeda980-9436-11ea-8a86-84020d9f2999.png)

Module configuration:  
![image](https://user-images.githubusercontent.com/20332546/81700440-a5430880-9436-11ea-8473-18d78c69d638.png)

___

As proof to myself that this disparity is really occurring, LDEW 48 2 is my project I made, LDEW 48 3 was made from adding instruments to your XML. My best guess is that it's got something to do with event 5 being created after the other events.

![image](https://user-images.githubusercontent.com/20332546/81701281-c821ec80-9437-11ea-814b-b750e46298cc.png)

**Comment by h3n0r1k** [comment]
hey!

I could reproduce the Bug with the XML you provided. It occured after:

1. delete visit 5 -> no bug
2. add visist 5 (its behind visit 6 wich has d as exception) -> no bug
3. swap visist 5 and 6 (5 is before 6 now) -> bug occurded

Thanks für your effort!

**Comment by ChemiKyle** [comment]
Hello @h3n0r1k,

Sorry for the delay, we have been quite busy with COVID related projects. At the end of last week we made a release that included a handful of fixes, many of which were addressing this issue; could you check if you can still recreate the issue with the current version?

**Comment by h3n0r1k** [comment]
hey @ChemiKyle  no problem!
I did some testing and couldnt reproduce the bug anymore!

**Comment by ChemiKyle** [comment]
Great! I'm going to close this issue, thanks for all the great feedback @h3n0r1k.
