### ISSUE TITLE
ldew doesnt work for first record in dag

### ISSUE THREAD

**Issue by h3n0r1k** [ctsit/linear_data_entry_workflow#53]
Hey!

I am using a test user on version 9.5.24. He has a DAG assigned wich has no records. When i create the first record i can access all forms, even with ldew configured. Creating any following record it works just fine. 

![ldew first record](https://user-images.githubusercontent.com/33369183/81550808-0b6d5400-9381-11ea-9bb6-44afab6721a0.png)

![ldew second record](https://user-images.githubusercontent.com/33369183/81550809-0c05ea80-9381-11ea-896c-4619a8023e32.png)

Both Screenshots are in the same environment. If you cant reproduce this Bug (?) ill provide the project xml.

BR
Hendrik

**Comment by ChemiKyle** [comment]
I am able to recreate this bug with a similar project XML you have provided. First record has all forms available until first form is filled in, subsequent records have LDEW act as expected from the start.

I was able to tell which forms exceptions you listed, but please include an XML and screenshot of configuration when creating an issue - this module can be a bit complicated so it speeds things up considerably to have these from the start.

**Comment by ChemiKyle** [comment]
Issue stems from this line:  
https://github.com/ctsit/linear_data_entry_workflow/blob/14375c4f88e2a1c38506a0f5e60afa88f21f2553/ExternalModule.php#L90

`$forms_status` is `false` when acting as a user in a DAG creating the first record, causing the following block to not run:  
https://github.com/ctsit/linear_data_entry_workflow/blob/14375c4f88e2a1c38506a0f5e60afa88f21f2553/ExternalModule.php#L105-109

**Comment by ChemiKyle** [comment]
Addressed by PR #54
