### ISSUE TITLE
'hook_every_page_top' error message

### ISSUE THREAD

**Issue by dyu8** [ctsit/linear_data_entry_workflow#57]
Hi:

From time to time, our users received this error message:

----------------------------------------------------
The 'hook_every_page_top' hook did not complete for the 'linear_data_entry_workflow' module because of the following error. Stack traces are unfortunately not available for this type of error:

Error Message: date(): Invalid date.timezone value 'PST', we selected the timezone 'UTC' for now.
File: C:\inetpub\wwwroot\redcap\redcap_v12.5.14\Classes\System.php
Line: 119

URL: https://dhsp2redcap.ph.lacounty.gov/redcap_v12.5.14/DataEntry/record_status_dashboard.php?pid=21
Server: dhsp2redcap.ph.lacounty.gov (PWDHSPRCAP03)
User: c252277
Project ID: 21
Module Name: Linear Data Entry Workflow (linear_data_entry_workflow)
Module Author(s): [pbc@ufl.edu](mailto:pbc@ufl.edu), [tls@ufl.edu](mailto:tls@ufl.edu), [kyle.chesney@ufl.edu](mailto:kyle.chesney@ufl.edu)
Run Time: 2 seconds
---------------------------------------------------

Please advise how to fix this issue.   Also, on numerous occasions, users could mark forms as "complete" with an Required Field unfilled.   We don't know how this could happen.

Thanks

**Comment by ChemiKyle** [comment]
Addressed this via email. The solution was an issue with the hosting server's timezone, changing to `PDT` is assumed to have solved the issue.  
Noteworthy discovery is that some timezones may not be respected in REDCap.
