### ISSUE TITLE
Add @DEFAULT_ON_VISIBLE action tag

### ISSUE THREAD

**Issue by pbchase** [ctsit/linear_data_entry_workflow#8]
The @DEFAULT action tag is incompatible with branching logic rules that hide a field where it is used. Branching logic wants all hidden fields to be blank. @DEFAULT populates any field where it is used as a new form is accessed even if that field is hidden by branching logic. 
It would be useful to have a new action tag that populates a default value as a field becomes visible. Such an action tag might be called @DEFAULT_ON_UNHIDDEN or @DEFAULT_ON_VISIBLE
It would probably be most useful to populate the field with its default value any time the field is made visible. It should not be restricted to the first load of the page. Instead, any time a field is unhidden by branching logic, the default value should be set.

**Comment by tbembersimeao** [comment]
Functionality moved to https://github.com/ctsit/auto_populate_fields.
